### ISSUE TITLE
[Notice] Movement of cloudos.yaml

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#501]
@dev4unet @hyokyungk @inno-cloudbarista @innodreamer 

- Cloud Driver 개발 시 다음 내용 참고해주시기 바랍니다. 
- 향후, 신규 Driver 추가 시에는 다음 설정 파일 정보도 추가해 주시기 바랍니다. 
  - `./cloud-driver-libs/cloudos_meta.yaml`
- 다음, 설정 파일은 서버 통합 시험 완료 후에 드라이버 공식 배포 시에 추가 하도록 하겠습니다. (@innodreamer, @powerkimhub) 
  - `./cloud-driver-libs/cloudos.yaml`

**[변화]**
- `./conf/cloudos.yaml` 파일을 `./cloud-driver-libs/cloudos.yaml`로 이동
  - 포함내용: 현재 서버가 지원하는 연동 CloudOS(CSP) 목록

**[사유]**
- 신규 Cloud driver 라이브러리의 추가 및 제거 시 변경되는(해야 하는) 파일들을 같은 위치에서 관리
- 이동한 대상 경로에 `./cloud-driver-libs/cloudos_meta.yaml` 파일도 신규 추가됨
  - 파일내용: 
    - CSP별로 Region 정보 입력 API 사용시 입력해야 하는 인자 이름 목록
    - CSP별로 Credential 정보 입력 API 사용시 입력해야 하는 인자 이름 목록
    - 예시
      ```
      AZURE:
        region: location ResourceGroup
        credential: ClientId ClientSecret TenantId SubscriptionId
      
      OPENSTACK:
        region: Region
        credential: IdentityEndpoint Username Password DomainName ProjectID

      ...

      ```
  - Key-Value 형식의 API 입력 인자 validation 처리 등에 활용 예정

**[적용]**
- https://github.com/cloud-barista/cb-spider/commit/624e6e726f8e7bb42e69057681a0f0c3debdc04c
