### ISSUE TITLE
[Cloudit] Check the image not found error

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#615]
- Image not found 오류 발생 환경에서,
- server에서 Cloudit driver StartVM 호출시 다음과 같이 reqInfoForDriver를 넘기고 있습니다. 
```
info, err := handler.StartVM(reqInfoForDriver)
```
- 넘기기 전 reqInfoForDriver 정보를 찍어보면, 다음과 같습니다. 

resources.VMReqInfo{
    IId:resources.IID{NameId:"vm-01-c9k2q6iba5o2iv4kbl80", SystemId:""}, 
    ImageIID:resources.IID{NameId:"**Ubuntu 18.04**", SystemId:"Ubuntu 18.04"}, 
    VpcIID:resources.IID{NameId:"vpc-01-c9k233qba5o1amd66lhg", SystemId:"vpc-01-c9k233qba5o1amd66lhg"}, 
    SubnetIID:resources.IID{NameId:"subnet-01-c9k233qba5o1amd66li0", SystemId:"e1e33162-feb8-4af0-a897-77dd0337b52e"},
    SecurityGroupIIDs:[]resources.IID{resources.IID{NameId:"sg01-c9k2352ba5o1amd66lig", SystemId:"0023349d-6187-49a3-ad0a-fd68533bf315"}}, 
    VMSpecName:"**small-2**", 
    KeyPairIID:resources.IID{NameId:"keypair-0-c9k237aba5o1amd66lj0", SystemId:"keypair-0-c9k237aba5o1amd66lj0"}, 
    RootDiskType:"", RootDiskSize:"", VMUserId:"cb-user", VMUserPasswd:""
}

- Image 이름(Ubuntu 18.04)을 포함하여 위 인자 값 설정에 문제가 있는지 확인 부탁드립니다. 
- driver 단에서 위 설정으로 VM 생성 한번 시험 부탁 드립니다. 
  - Cloudit Console로는 "Ubuntu 18.04" image로 VM 생성이 잘되는 것은 확인하였습니다.

**Comment by inno-cloudbarista** [comment]
ImageIID:resources.IID{NameId:"Ubuntu 18.04", SystemId:"Ubuntu 18.04"},

이전에 타 CSP는 Image의 경우 SystemId로 모두 동일하게 가져가는 걸로 되어 있는데, 

Cloudit의 경우 이전처럼 NameId, SystemId를 각각 다르게 가져가는 걸로 되어 있습니다.

{NameId:"Ubuntu 18.04", SystemId:"ee441331-0872-49c3-8??"} 
{NameId:"Ubuntu 18.04", SystemId:""} 
{NameId:"", SystemId:"ee441331-0872-49c3-8??"}
위의 경우일 때는 조회되어지지만 {NameId:"Ubuntu 18.04", SystemId:"Ubuntu 18.04"}는 조회 실패하게 됩니다.

Cloudit, Openstack 모두 NameId를 SystemId로 사용하게끔 변경하도록 하겠습니다.

{NameId:"ee441331-0872-49c3-8??", SystemId:"ee441331-0872-49c3-8??"}

**Comment by powerkimhub** [comment]
@inno-cloudbarista 

### Image 정보 관련

기본 방향은 사용자는 가독성이 좋은 User NameId를 사용하는 것입니다.
가능하다면 사용자에게 가독성이 떨어지는 UUID 스타일의 ID는 피하면 좋을 것 같습니다. 
다음 사항 다시 한번 확인 부탁 드립니다.

[질문] User NameId(Ubuntu 18.04)의 identity가 보장되는지요?
- (1) Yes, 이미지의 중복 이름 사용 불가, ID로 사용 가능
- (2) No, 이미지의 중복 이름 사용 가능, ID로 사용 불가능

- (1)의 경우 가독성이 좋은 User NameId로 모두 맞추면 좋을 것 같습니다. 
  - 이미지 정보/목록으로 제공되는 ID의 NameId(ex: Ubuntu 18.04) 
  - VM 생성 인자로 넘기는 ID (사용자는 이미지 목록/정보를 통해서 NameId를 얻어서 이 ID를 VM 생성에 사용)
    - (참고: 기본적으로 사용자는 SystemId는 사용하지 않습니다. )
    - (참고: 이미지의 경우 create 과정이 없기 때문에, Server에서도 SystemId 정보는 알고 있지 않습니다..)
    - 만일, driver 단에서 vm 생성 요청시 UUID가 필요하다면,
      -  `Ubuntu 18.04`가 유일하기 때문에 driver 내부에서 대상 이미지의 UUID를 얻어서 처리 가능하리라 생각됩니다. 

- (2)의 경우 부득이 올려 주신 PR 618 처럼 UUID 중심으로 처리할 수 밖에 없을 것 같습니다. 
  - 이 경우에는 Image Get/List 반환 값의 NameId에도 UUID 형식으로 제공해주셔야 합니다. 
  - 사유: 사용자는 이미지 목록/정보를 통해서 NameId를 얻어서 이 ID를 VM 생성에 사용 (SystemId가 아닌)
  - 현재 제공 정보는 다음과 같고, 사용자는 VM 생성시 `Ubuntu 18.04`를 넘기고 있어 오류가 발생합니다. 
    - UUID를 명시적으로 설정하면 VM은 잘 생성되고 있습니다.  
    - spctl 이미지 정보 예시
      ```
      ubuntu@nodedev2:interface# ./spctl image list --cname cloudit-config01
      image:
      - IId:
          NameId: Ubuntu 18.04
          SystemId: ee441331-0872-49c3-886c-1873a6e32e09
        GuestOS: Ubuntu 18.04 LTS
        Status: COMPLETED
        KeyValueList: null
      - IId:
          NameId: CentOS 7.8
          SystemId: fa2b8818-3009-4cf2-8550-dbe20b1b42fb
        GuestOS: CentOS 7
        Status: COMPLETED
        KeyValueList: null
      ```
  - AdminWeb 이미지 정보 예시: ![image](https://user-images.githubusercontent.com/46367962/166094503-97e2bb95-0fa0-44ba-aa3a-c43aa9896c99.png)


---

### VM cb-user 설정 및 SSH 로그인 이슈

- 시험 과정에서 다음 위치의 timeout 시간이 부족한 경우가 있었습니다.
  - 저에 경우 60에서도 오류가 발생한 경우가 있었습니다. 
  - 120으로 추천 드립니다. 
  ```diff
  - VMHandler.go:231         maxConnectionRetryCnt := 30
  + VMHandler.go:231         maxConnectionRetryCnt := 120
  ```

- VM 생성 후 cb-user@ssh 로그인 시도 해보니, `Permission denied`가 자주 발생하고 있습니다. 
  - Test 도구 및 AdminWeb 환경에서도 동일합니다. (5회 정도에서 1회 성공)
  - ssh 로그인이 성공했어도, 몇 차례 로그인을 하다보면, 
    - Permission denied 상태로 바뀌어 버리는 증상도 있습니다. 
  - Driver 단에서 여러 차례 반복 확인 시험 부탁 드립니다.
