### ISSUE TITLE
[Tencent] Something wrong when creating cb-user and more...

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#650]
@choryang @dogfootman @dev4unet

- 증상: I/O Rule 검증 시험이 All Pass하다 Fail 나다가 불안정함
- 분석 결과 Key 관련 2가지 이슈와 연관 이슈 1가지가 존재합니다. 
  - 확인 부탁드립니다.

- #### [Issue-I] 이전 Test 완료 후 clear 시 Key가 안지워진 경우
    - VM 삭제 후 key 삭제 시에 보통 한동안 `사용 중인 VM 존재 오류` 발생합니다.
    - 이 경우를 위해서 검증 시험에서는 보통 30번(약 30sec) 시도로 거의 삭제 되었습니다. 
    - Tencent 경우 반복 시험을 여러번 해보니, 30회 이상 시도에도 삭제되지 않고 버티는 경우가 종종 발생했습니다.
    - 이 경우 이미 동일 Key가 존재하기 때문에 Key 생성시에 local에 저장하는 private 키가 받아지지 않으며,
    - 이후 ssh 명령 실행 오류로 Rule 검증 시험 일부 Fail 상태
    - **Test Scriipt 내 삭제를 120회 시도로 늘려서 해결** (이 껀은 이슈 요청 보다는 현황 공유입니다.)

- #### [Issue-2] VM 내부 cb-user Key 설정 이슈
  - tencent는 cloud-init을 이용하여 다음 스크립트를 태워서 cb-user 계정을 추가하고 있습니다. 
    - `cb-spider/cloud-driver-libs/.cloud-init-tencent`
    - 이중 VM 내부에서 다음 명령 실행이 성공하거나 못하거나에 따라 
      - 외부에서 cb-user 계정 접근이 가능했다 못했다 하는 현상이 발생하고 있습니다.
      - `curl -s http://169.254.0.23/latest/meta-data/public-keys/0/openssh-key > /home/cb-user/.ssh/authorized_keys`
    - 문제가 발생할때 VM 내부 현황(cb-user 계정 로그인 불가능, ubuntu 계정으로 로그인 후 확인)
      ```html
        cat /home/cb-user/.ssh/authorized_keys
        
        <html>
          <head>
            <title> 404 - Not Found </title>
            <body>
                  <h1> 404 - Not Found </h1>
            </body>
          </head>
        </html>
      ```
  - 추정: cloud-init meta 정보 서버가 올라오기 전에 culr fetch가 요청되는 걸로 보입니다. 
    - 동일 VM에 들어가서 curl fetch를 실행해보면 해당 Key를 잘 가져 옵니다. 
  - **관련 사항 확인 및 보완 부탁드립니다.** 

- #### [Issue-3] VM 반환 정보 중 Key Systme ID 공백 
  - 다음과 같이 VM 생성시 반환되는 VM 정보에 Key에 대한  SystemId가 없이 올라오는 경우가 많습니다.
  - Issue-2와 연관된 이슈일 수도 있겠습니다. 점검 부탁드립니다. 

  ```
  ...
  
  SecurityGroupIIds:
  - NameId: SG-Rules-Test-SG01
    SystemId: sg-nln0ezar
  KeyPairIId:
    NameId: SG-Rules-Test-keypair-01
    SystemId: ""   <============================= ???
  ...
  ```
